import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

train = pd.read_csv('data/spr_bench_train.csv')
feature_cols = [c for c in train.columns if c.startswith('token_')]

# The task is "LabelNoiseCeiling".
# The SOTA is 70%.
# We have tried everything and cannot get above 55% validation accuracy.
# This means the labels are NOT generated by a simple rule with 30% noise.
# What if the labels are generated by a rule that is EXACTLY 70% accurate on the training set, but the rule itself is very complex?
# Or what if the labels are generated by a rule, but the noise is NOT random?
# What if the noise is adversarial?

# Let's look at the SOTA again. "The current state-of-the-art accuracy on SPR_BENCH is 70%."
# This is a benchmark. Benchmarks usually have a clear, deterministic rule, and the SOTA is just the best model so far.
# If the SOTA is 70%, it means the best model so far has only achieved 70%.
# This implies the rule is deterministic, but very hard to learn.
# But we trained an MLP and got 100% train accuracy, and 53% val accuracy.
# This means the MLP perfectly memorized the training set, but failed to generalize.
# This happens when the rule is too complex for the MLP's inductive bias, OR when the labels are random.
# Since SOTA is 70%, the labels are NOT random.

# Let's try to find a rule that is based on the *parity* of the sequence.
# For example, "number of red tokens is even AND number of blue tokens is odd".

shapes = ['T', 'S', 'C', 'D']
colors = ['r', 'g', 'b', 'y']

best_acc = 0
best_rule = ""

def check_rule(preds, name):
    global best_acc, best_rule
    acc = accuracy_score(train['label'], preds)
    if acc < 0.5:
        acc = 1 - acc
        name = f"NOT ({name})"
    if acc > best_acc:
        best_acc = acc
        best_rule = name
    if acc > 0.65:
        print(f"Rule: {name}, Acc: {acc:.4f}")

# Let's try to find a rule that is based on the *number of transitions* between shapes or colors.
# 65. Number of shape transitions > threshold
for i in range(1, 8):
    preds = train[feature_cols].apply(lambda x: sum(1 for j in range(len(x)-1) if x[j][0] != x[j+1][0]) > i, axis=1)
    check_rule(preds, f"shape transitions > {i}")

# 66. Number of color transitions > threshold
for i in range(1, 8):
    preds = train[feature_cols].apply(lambda x: sum(1 for j in range(len(x)-1) if x[j][1] != x[j+1][1]) > i, axis=1)
    check_rule(preds, f"color transitions > {i}")

# 67. Number of token transitions > threshold
for i in range(1, 8):
    preds = train[feature_cols].apply(lambda x: sum(1 for j in range(len(x)-1) if x[j] != x[j+1]) > i, axis=1)
    check_rule(preds, f"token transitions > {i}")

print(f"\nBest rule: {best_rule} with accuracy {best_acc:.4f}")
