import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

train = pd.read_csv('data/spr_bench_train.csv')
feature_cols = [c for c in train.columns if c.startswith('token_')]

# Let's try to find the rule by looking at the SOTA reference again.
# "The current state-of-the-art accuracy on SPR_BENCH is 70%."
# This could mean that the best model achieves 70% accuracy.
# But what if the rule is deterministic, and the SOTA model just hasn't found it?
# Or what if the labels are generated by a rule, but with 30% noise?
# If the labels are generated by a rule with 30% noise, then the true rule should have ~70% accuracy on the training set.
# But we haven't found any rule with >54% accuracy.
# This suggests that the rule is NOT a simple 1-token or 2-token rule.
# It must be a more complex rule.

# Let's try to train a model that can learn complex rules, like a Transformer or a deep CNN.
# But wait, we already trained an MLP and it got 100% train accuracy and 53% val accuracy.
# This means the MLP perfectly memorized the training set, but failed to generalize.
# This is a classic sign of either:
# 1. The rule is too complex for the MLP's inductive bias.
# 2. The labels are completely random (but SOTA is 70%, so this is false).
# 3. The labels are noisy, and the MLP overfit the noise.

# If the labels are noisy, we need to use strong regularization to prevent overfitting the noise.
# We tried L1/L2 regularization, low depth trees, etc., and the best val accuracy was ~54%.
# This means our models are not capturing the true rule at all.

# Let's rethink the problem. The tokens are shapes and colors.
# Maybe the rule is based on the sequence of shapes or colors.
# Let's try to extract more sequence-based features.

shapes = ['T', 'S', 'C', 'D']
colors = ['r', 'g', 'b', 'y']

best_acc = 0
best_rule = ""

def check_rule(preds, name):
    global best_acc, best_rule
    acc = accuracy_score(train['label'], preds)
    if acc < 0.5:
        acc = 1 - acc
        name = f"NOT ({name})"
    if acc > best_acc:
        best_acc = acc
        best_rule = name
    if acc > 0.65:
        print(f"Rule: {name}, Acc: {acc:.4f}")

# 40. Longest consecutive sequence of same shape
def longest_same_shape(row):
    max_len = 1
    current_len = 1
    for i in range(1, len(row)):
        if row[i][0] == row[i-1][0]:
            current_len += 1
            max_len = max(max_len, current_len)
        else:
            current_len = 1
    return max_len

preds = train[feature_cols].apply(longest_same_shape, axis=1)
for i in range(1, 9):
    check_rule(preds == i, f"longest same shape == {i}")
    check_rule(preds >= i, f"longest same shape >= {i}")

# 41. Longest consecutive sequence of same color
def longest_same_color(row):
    max_len = 1
    current_len = 1
    for i in range(1, len(row)):
        if row[i][1] == row[i-1][1]:
            current_len += 1
            max_len = max(max_len, current_len)
        else:
            current_len = 1
    return max_len

preds = train[feature_cols].apply(longest_same_color, axis=1)
for i in range(1, 9):
    check_rule(preds == i, f"longest same color == {i}")
    check_rule(preds >= i, f"longest same color >= {i}")

# 42. Number of transitions between shapes
def shape_transitions(row):
    return sum(1 for i in range(1, len(row)) if row[i][0] != row[i-1][0])

preds = train[feature_cols].apply(shape_transitions, axis=1)
for i in range(8):
    check_rule(preds == i, f"shape transitions == {i}")

# 43. Number of transitions between colors
def color_transitions(row):
    return sum(1 for i in range(1, len(row)) if row[i][1] != row[i-1][1])

preds = train[feature_cols].apply(color_transitions, axis=1)
for i in range(8):
    check_rule(preds == i, f"color transitions == {i}")

print(f"\nBest rule: {best_rule} with accuracy {best_acc:.4f}")
