import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

train = pd.read_csv('data/spr_bench_train.csv')
feature_cols = [c for c in train.columns if c.startswith('token_')]

# The task is "LabelNoiseCeiling".
# The SOTA is 70%.
# We have tried EVERYTHING and cannot get above 55% validation accuracy.
# This means the labels are NOT generated by a simple rule with 30% noise.
# If they were, our models would have found it.
# What if the labels are generated by a rule that is EXACTLY 70% accurate on the training set, but the rule itself is very complex?
# Or what if the labels are generated by a rule, but the noise is NOT random?
# What if the noise is adversarial?

# Let's look at the SOTA again. "The current state-of-the-art accuracy on SPR_BENCH is 70%."
# This is a benchmark. Benchmarks usually have a clear, deterministic rule, and the SOTA is just the best model so far.
# If the SOTA is 70%, it means the best model so far has only achieved 70%.
# This implies the rule is deterministic, but very hard to learn.
# But we trained an MLP and got 100% train accuracy, and 53% val accuracy.
# This means the MLP perfectly memorized the training set, but failed to generalize.
# This happens when the rule is too complex for the MLP's inductive bias, OR when the labels are random.
# Since SOTA is 70%, the labels are NOT random.

# Let's try to find a rule that is based on the *parity* of the sequence.
# For example, "number of red tokens is even AND number of blue tokens is odd".

shapes = ['T', 'S', 'C', 'D']
colors = ['r', 'g', 'b', 'y']

best_acc = 0
best_rule = ""

def check_rule(preds, name):
    global best_acc, best_rule
    acc = accuracy_score(train['label'], preds)
    if acc < 0.5:
        acc = 1 - acc
        name = f"NOT ({name})"
    if acc > best_acc:
        best_acc = acc
        best_rule = name
    if acc > 0.65:
        print(f"Rule: {name}, Acc: {acc:.4f}")

# 55. Parity of counts of all shapes
import itertools
for p in itertools.product([0, 1], repeat=4):
    preds = train[feature_cols].apply(lambda x: all(sum(1 for t in x if t[0] == shapes[i]) % 2 == p[i] for i in range(4)), axis=1)
    check_rule(preds, f"shape parities == {p}")

# 56. Parity of counts of all colors
for p in itertools.product([0, 1], repeat=4):
    preds = train[feature_cols].apply(lambda x: all(sum(1 for t in x if t[1] == colors[i]) % 2 == p[i] for i in range(4)), axis=1)
    check_rule(preds, f"color parities == {p}")

# 57. Number of tokens that are 'Tr' or 'Sg' or ...
for t1, t2 in itertools.combinations([f"{s}{c}" for s in shapes for c in colors], 2):
    preds = train[feature_cols].apply(lambda x: sum(1 for t in x if t in (t1, t2)) > 2, axis=1)
    check_rule(preds, f"count {t1} or {t2} > 2")

print(f"\nBest rule: {best_rule} with accuracy {best_acc:.4f}")
